const { contextBridge, ipcRenderer } = require('electron');

contextBridge.exposeInMainWorld('pt', {
  sendState: (s) => ipcRenderer.send('state', s),
  ackOutput: (payload) => ipcRenderer.send('output-rendered', payload),
  sendControlStatus: (status) => ipcRenderer.send('control-status', status),
  onState: (cb) => ipcRenderer.on('state', (e, s) => cb(s)),
  openOutput: (displayId) => ipcRenderer.send('open-output', displayId),
  sendToDisplay: (displayId) => ipcRenderer.send('send-to-display', displayId),
  closeOutput: () => ipcRenderer.send('close-output'),
  toggleFullscreen: () => ipcRenderer.send('toggle-fullscreen'),
  exitFullscreen: () => ipcRenderer.send('exit-fullscreen'),
  setOnTop: (flag) => ipcRenderer.send('ctl-on-top', flag),
  getDisplays: () => ipcRenderer.invoke('displays'),
  isOutputOpen: () => ipcRenderer.invoke('output-open'),
  getOutputConfigs: () => ipcRenderer.invoke('output-configs'),
  setOutputConfigs: (configs) => ipcRenderer.send('set-output-configs', configs),
  mediaSave: (payload) => ipcRenderer.invoke('media-save', payload),
  ltPackageExport: (payload) => ipcRenderer.invoke('lt-package-export', payload),
  ltPackageImport: (payload) => ipcRenderer.invoke('lt-package-import', payload),
  showStorageStatus: () => ipcRenderer.invoke('show-storage-status'),
  showStorageSave: (payload) => ipcRenderer.invoke('show-storage-save', payload),
  showStorageLoadCurrent: () => ipcRenderer.invoke('show-storage-load-current'),
  showStorageRecover: (choice) => ipcRenderer.invoke('show-storage-recover', choice),
  showPackageExport: (payload) => ipcRenderer.invoke('show-package-export', payload),
  showPackageImport: (payload) => ipcRenderer.invoke('show-package-import', payload),
  showFolderImport: (payload) => ipcRenderer.invoke('show-folder-import', payload),
  showPreflightInspect: (payload) => ipcRenderer.invoke('show-preflight-inspect', payload),
  getNetworkInfo: () => ipcRenderer.invoke('network-info'),
  identifyDisplays: () => ipcRenderer.invoke('identify-displays'),
  onDisplays: (cb) => ipcRenderer.on('displays', (e, list) => cb(list)),
  onOutputState: (cb) => ipcRenderer.on('output-state', (e, open) => cb(open)),
  onOutputConfigState: (cb) => ipcRenderer.on('output-config-state', (e, state) => cb(state)),
  onNetworkInfo: (cb) => ipcRenderer.on('network-info', (e, info) => cb(info)),
  onRemoteCmd: (cb) => ipcRenderer.on('remote-cmd', (e, cmd) => cb(cmd)),
  qr: (text) => ipcRenderer.invoke('qr', text),
  shareStart: () => ipcRenderer.invoke('share-start'),
  shareStop: () => ipcRenderer.invoke('share-stop'),
  shareInfo: () => ipcRenderer.invoke('share-info'),
  onShareInfo: (cb) => ipcRenderer.on('share-info', (e, info) => cb(info)),
  fitWindow: (h) => ipcRenderer.send('fit-window', h),
  onWinFs: (cb) => ipcRenderer.on('win-fs', (e, v) => cb(v)),
  buildInfo: () => ipcRenderer.invoke('build-info')
});
