const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('pt', {
  sendState: (s) => ipcRenderer.send('state', s),
  ackOutput: (payload) => ipcRenderer.send('output-rendered', payload),
  sendControlStatus: (status) => ipcRenderer.send('control-status', status),
  onState: (cb) => ipcRenderer.on('state', (e, s) => cb(s)),
  openOutput: (displayId) => ipcRenderer.send('open-output', displayId),
  sendToDisplay: (displayId) => ipcRenderer.send('send-to-display', displayId),
  closeOutput: () => ipcRenderer.send('close-output'),
  toggleFullscreen: () => ipcRenderer.send('toggle-fullscreen'),
  exitFullscreen: () => ipcRenderer.send('exit-fullscreen'),
  setOnTop: (flag) => ipcRenderer.send('ctl-on-top', flag),
  getDisplays: () => ipcRenderer.invoke('displays'),
  isOutputOpen: () => ipcRenderer.invoke('output-open'),
  getOutputConfigs: () => ipcRenderer.invoke('output-configs'),
  setOutputConfigs: (configs) => ipcRenderer.send('set-output-configs', configs),
  mediaImportFile: (file, options = {}) => ipcRenderer.invoke('media-import-file', {
    path: webUtils.getPathForFile(file),
    name: file && file.name,
    type: file && file.type,
    size: file && file.size,
    storage: options && options.storage
  }),
  mediaSave: (payload) => ipcRenderer.invoke('media-save', payload),
  ltPackageExport: (payload) => ipcRenderer.invoke('lt-package-export', payload),
  ltPackageImport: (payload) => ipcRenderer.invoke('lt-package-import', payload),
  showStorageStatus: () => ipcRenderer.invoke('show-storage-status'),
  showStorageSave: (payload) => ipcRenderer.invoke('show-storage-save', payload),
  showStorageLoadCurrent: () => ipcRenderer.invoke('show-storage-load-current'),
  showStorageRecover: (choice) => ipcRenderer.invoke('show-storage-recover', choice),
  showDocumentStatus: () => ipcRenderer.invoke('show-document-status'),
  showDocumentSave: (payload) => ipcRenderer.invoke('show-document-save', payload),
  showDocumentOpen: (payload) => ipcRenderer.invoke('show-document-open', payload),
  showDocumentClearPath: () => ipcRenderer.send('show-document-clear-path'),
  showPackageExport: (payload) => ipcRenderer.invoke('show-package-export', payload),
  showPackageImport: (payload) => ipcRenderer.invoke('show-package-import', payload),
  showFolderImport: (payload) => ipcRenderer.invoke('show-folder-import', payload),
  showPreflightInspect: (payload) => ipcRenderer.invoke('show-preflight-inspect', payload),
  getNetworkInfo: () => ipcRenderer.invoke('network-info'),
  identifyDisplays: () => ipcRenderer.invoke('identify-displays'),
  onDisplays: (cb) => ipcRenderer.on('displays', (e, list) => cb(list)),
  onOutputState: (cb) => ipcRenderer.on('output-state', (e, open) => cb(open)),
  onOutputConfigState: (cb) => ipcRenderer.on('output-config-state', (e, state) => cb(state)),
  onNetworkInfo: (cb) => ipcRenderer.on('network-info', (e, info) => cb(info)),
  onRemoteCmd: (cb) => ipcRenderer.on('remote-cmd', (e, cmd) => cb(cmd)),
  qr: (text) => ipcRenderer.invoke('qr', text),
  shareStart: () => ipcRenderer.invoke('share-start'),
  shareStop: () => ipcRenderer.invoke('share-stop'),
  shareInfo: () => ipcRenderer.invoke('share-info'),
  onShareInfo: (cb) => ipcRenderer.on('share-info', (e, info) => cb(info)),
  fitWindow: (h) => ipcRenderer.send('fit-window', h),
  onWinFs: (cb) => ipcRenderer.on('win-fs', (e, v) => cb(v)),
  buildInfo: () => ipcRenderer.invoke('build-info'),
  liveInputDesktopSources: () => ipcRenderer.invoke('live-input-desktop-sources'),
  liveInputDevices: (requestPermission = false) => ipcRenderer.invoke('live-input-devices', ['camera', 'microphone'].includes(requestPermission) ? requestPermission : requestPermission === true),
  liveInputPermissions: () => ipcRenderer.invoke('live-input-permissions'),
  openPrivacySettings: (section) => ipcRenderer.invoke('open-privacy-settings', ['screen', 'camera', 'microphone'].includes(section) ? section : ''),
  liveInputConfigure: (definitions) => ipcRenderer.invoke('live-input-configure', definitions),
  liveInputRestart: (inputId) => ipcRenderer.invoke('live-input-restart', inputId),
  liveInputStatuses: () => ipcRenderer.invoke('live-input-statuses'),
  liveInputSubscribe: (inputId) => ipcRenderer.invoke('live-input-subscribe', inputId),
  liveInputUnsubscribe: (inputId) => ipcRenderer.send('live-input-unsubscribe', inputId),
  liveInputSignalToHub: (payload) => ipcRenderer.invoke('live-input-signal-to-hub', payload),
  onLiveInputSignal: (cb) => ipcRenderer.on('live-input-signal', (event, payload) => cb(payload)),
  onLiveInputStatus: (cb) => ipcRenderer.on('live-input-status', (event, payload) => cb(payload))
});
